import { writeFile } from 'node:fs/promises';
import type { RunMetrics } from './types.js';

export function createEmptyRunMetrics(): RunMetrics {
  return {
    seenTotal: 0,
    deletedTotal: 0,
    disabledTotal: 0,
    enabledTotal: 0,
    keptTotal: 0,
    skippedTotal: 0,
    prunedStateEntriesTotal: 0,
    stateChanged: 0,
    stateNormalized: 0,
    stateRecovered: 0,
    probeTotal: 0,
    probeOkTotal: 0,
    probeStatus401Total: 0,
    probeFailedTotal: 0,
    probeDurationSecondsSum: 0,
    stateSaveDurationSeconds: 0,
    managedDisabled: 0,
    stateEntries: 0,
    suspiciousCandidates: 0,
    managedDisabledCandidates: 0,
    healthySampleCandidates: 0,
    errorsTotal: 0,
    runDurationSeconds: 0,
    runTimestampSeconds: 0
  };
}

export async function writePrometheusTextfile(filePath: string, metrics: RunMetrics): Promise<void> {
  const lines = [
    '# HELP cpa_authfiles_seen_total Number of auth files seen in this run',
    '# TYPE cpa_authfiles_seen_total gauge',
    `cpa_authfiles_seen_total ${metrics.seenTotal}`,
    '# HELP cpa_authfiles_deleted_total Number of auth files deleted in this run',
    '# TYPE cpa_authfiles_deleted_total gauge',
    `cpa_authfiles_deleted_total ${metrics.deletedTotal}`,
    '# HELP cpa_authfiles_disabled_total Number of auth files disabled in this run',
    '# TYPE cpa_authfiles_disabled_total gauge',
    `cpa_authfiles_disabled_total ${metrics.disabledTotal}`,
    '# HELP cpa_authfiles_enabled_total Number of auth files enabled in this run',
    '# TYPE cpa_authfiles_enabled_total gauge',
    `cpa_authfiles_enabled_total ${metrics.enabledTotal}`,
    '# HELP cpa_authfiles_kept_total Number of auth files kept in this run',
    '# TYPE cpa_authfiles_kept_total gauge',
    `cpa_authfiles_kept_total ${metrics.keptTotal}`,
    '# HELP cpa_authfiles_skipped_total Number of auth files skipped in this run',
    '# TYPE cpa_authfiles_skipped_total gauge',
    `cpa_authfiles_skipped_total ${metrics.skippedTotal}`,
    '# HELP cpa_authfiles_state_pruned_total Number of stale local state entries pruned in this run',
    '# TYPE cpa_authfiles_state_pruned_total gauge',
    `cpa_authfiles_state_pruned_total ${metrics.prunedStateEntriesTotal}`,
    '# HELP cpa_authfiles_state_changed Whether local state content changed in this run',
    '# TYPE cpa_authfiles_state_changed gauge',
    `cpa_authfiles_state_changed ${metrics.stateChanged}`,
    '# HELP cpa_authfiles_state_normalized Whether loaded local state needed normalization in this run',
    '# TYPE cpa_authfiles_state_normalized gauge',
    `cpa_authfiles_state_normalized ${metrics.stateNormalized}`,
    '# HELP cpa_authfiles_state_recovered Whether a broken state file was recovered in this run',
    '# TYPE cpa_authfiles_state_recovered gauge',
    `cpa_authfiles_state_recovered ${metrics.stateRecovered}`,
    '# HELP cpa_authfiles_probe_total Number of probes attempted in this run',
    '# TYPE cpa_authfiles_probe_total gauge',
    `cpa_authfiles_probe_total ${metrics.probeTotal}`,
    '# HELP cpa_authfiles_probe_ok_total Number of successful probes in this run',
    '# TYPE cpa_authfiles_probe_ok_total gauge',
    `cpa_authfiles_probe_ok_total ${metrics.probeOkTotal}`,
    '# HELP cpa_authfiles_probe_status401_total Number of probes that returned 401 in this run',
    '# TYPE cpa_authfiles_probe_status401_total gauge',
    `cpa_authfiles_probe_status401_total ${metrics.probeStatus401Total}`,
    '# HELP cpa_authfiles_probe_failed_total Number of failed non-401 probes in this run',
    '# TYPE cpa_authfiles_probe_failed_total gauge',
    `cpa_authfiles_probe_failed_total ${metrics.probeFailedTotal}`,
    '# HELP cpa_authfiles_probe_duration_seconds_sum Sum of probe durations in seconds',
    '# TYPE cpa_authfiles_probe_duration_seconds_sum gauge',
    `cpa_authfiles_probe_duration_seconds_sum ${metrics.probeDurationSecondsSum.toFixed(6)}`,
    '# HELP cpa_authfiles_state_save_duration_seconds Time spent saving local state in this run',
    '# TYPE cpa_authfiles_state_save_duration_seconds gauge',
    `cpa_authfiles_state_save_duration_seconds ${metrics.stateSaveDurationSeconds.toFixed(6)}`,
    '# HELP cpa_authfiles_managed_disabled Number of currently tool-managed disabled auth files',
    '# TYPE cpa_authfiles_managed_disabled gauge',
    `cpa_authfiles_managed_disabled ${metrics.managedDisabled}`,
    '# HELP cpa_authfiles_state_entries Number of state entries tracked locally',
    '# TYPE cpa_authfiles_state_entries gauge',
    `cpa_authfiles_state_entries ${metrics.stateEntries}`,
    '# HELP cpa_authfiles_candidates_total Candidate counts by kind in this run',
    '# TYPE cpa_authfiles_candidates_total gauge',
    `cpa_authfiles_candidates_total{kind="suspicious"} ${metrics.suspiciousCandidates}`,
    `cpa_authfiles_candidates_total{kind="managed_disabled"} ${metrics.managedDisabledCandidates}`,
    `cpa_authfiles_candidates_total{kind="healthy_sample"} ${metrics.healthySampleCandidates}`,
    '# HELP cpa_authfiles_errors_total Internal errors seen in this run',
    '# TYPE cpa_authfiles_errors_total gauge',
    `cpa_authfiles_errors_total ${metrics.errorsTotal}`,
    '# HELP cpa_authfiles_run_duration_seconds Total run duration in seconds',
    '# TYPE cpa_authfiles_run_duration_seconds gauge',
    `cpa_authfiles_run_duration_seconds ${metrics.runDurationSeconds.toFixed(6)}`,
    '# HELP cpa_authfiles_run_timestamp_seconds Unix timestamp when this run finished',
    '# TYPE cpa_authfiles_run_timestamp_seconds gauge',
    `cpa_authfiles_run_timestamp_seconds ${metrics.runTimestampSeconds}`
  ];

  await writeFile(filePath, `${lines.join('\n')}\n`, 'utf8');
}
